### ISSUE TITLE
Unhandled Exception when using Generics 

### ISSUE THREAD

**Issue by chimon2000** [xsahil03x/super_enum#22]
When using generics, I am getting a type casting exceptions given the following example

```dart
@superEnum
enum _ModelState {
  @generic
  @Data(fields: [DataField('data', Generic)])
  Success,

  @object
  Error,

  @object
  Loading,

  @object
  Empty,
}

//Somewhere else in code
Stream<ModelState<int>> getSomething() {
  return Stream.fromFuture(Future.value(1))
      .publishReplay(maxSize: 1)
      .refCount()
      .map((data) => ModelState.loading());
}
```

The error: 

```
Unhandled Exception: type 'Loading<dynamic>' is not a subtype of type 'Loading<int>'
```

Environment:

```bash
Flutter 1.12.13+hotfix.6
Framework • revision 18cd7a3601 (7 days ago) • 2019-12-11 06:35:39 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0
```

Dependencies:

```yaml
dependencies:
  super_enum: ^0.2.0

dev_dependencies:
  super_enum_generator: ^0.2.0+1
  build_runner: ^1.7.1
```
