### ISSUE TITLE
Release null safe version ?

### ISSUE THREAD

**Issue by FatulM** [xsahil03x/super_enum#69]
Hi,
Do you have any plan to release null safe version of the library ?

Thanks.

**Comment by ride4sun** [comment]
I am getting this problem with Flutter 2.0, is this package getting updated? No is fine but please give us a hint.

Because super_enum_generator >=0.2.0+1 depends on build >=0.12.6 <2.0.0 and chkobd depends on build ^2.0.0, super_enum_generator >=0.2.0+1 is forbidden.
So, because chkobd depends on super_enum_generator ^0.6.0, version solving failed.
pub get failed (1; So, because chkobd depends on super_enum_generator ^0.6.0, version solving failed.)

**Comment by ride4sun** [comment]
@xsahil03x The only thing to make super_enum ok for 2.0 is changing the build version in super_enum_generator.
Could you please do that?

**Comment by FatulM** [comment]
There are some other problems ...
For example in whenPartial the arguments should be nullable, but in the generated code they don't have `?` sign so they are non-null .
@ride4sun

**Comment by FatulM** [comment]
And for another example when method's return type should be nullable, so we can have void functions ...
Since `void` is `Object?` not `Object`

**Comment by ride4sun** [comment]
@FatulM Ok I just needed something which build for 2.0 and I got dependency errors for the build you reference.
This would be an easy fix and not take in account the null safety issues but helps people which have the same issues
I created two separate packages based on your code because the Android X updates where not done and the build dependency Issues

Here it is if other people have the same problem:
https://github.com/ride4sun/super_enum
https://github.com/ride4sun/super_enum_generator

They can be referenced in the yaml file like this:
```
dependencies:
  super_enum:
    git:
      url: https://github.com/ride4sun/super_enum.git
      ref: "0.6.0"

dev_dependencies:
  build_runner: ^1.12.2
  build: ^2.0.0
  built_value_generator: ^8.0.4
  built_value_test: ^8.0.4
  # flutter packages pub run build_runner watch --delete-conflicting-outputs

  super_enum_generator:
    git:
      url: https://github.com/ride4sun/super_enum_generator.git
      ref: "0.6.0"
```
